# Generated by Django 6.0.4 on 2026-06-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('interlock', 'Interlock'), ('chimney', 'Chimney'), ('masonry', 'Masonry'), ('patio', 'Patio'), ('driveway', 'Driveway'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
