# Generated by Django 6.0.4 on 2026-06-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('interlock', 'Interlock'), ('masonry', 'Masonry'), ('chimney', 'Chimney Repair'), ('patio', 'Patios & Walkways'), ('retaining_wall', 'Retaining Walls'), ('stonework', 'Custom Stonework'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
